criando arquivos
miziaalmeida/FIPE-Desafio pull request #1
Opened 2024-02-05 19:36 UTC by jeiellima

2024-02-22 17:14 UTC, miziaalmeida requested changes

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Common/APIManager.swift
> +
Podemos utilizar [enums para definir](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations) constantes e mesmo tipos específicos que visem retornar valores seguros para o seu código. Nós podemos criar enums de qq typo, e nesse caso para strings, ficaria da seguinte forma:

```
enum Constants {
    static let environment = "https://parallelum.com.br/fipe/api/v1/carros/marcas"
}
```

e vc poderia usar da forma abaixo, isso evita redundância de valores, [boilerplates](https://www.freecodecamp.org/portuguese/news/o-que-e-um-boilerplate-e-por-que-o-usamos-a-necessidade-de-um-guia-de-estilo-de-codigo/), e para valores inteiros, double, float .. evita [magic numbers](https://refactoring.guru/pt-br/replace-magic-number-with-symbolic-constant)

let url = URL(string: Constants.environment)!

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Common/APIManager.swift
> +
Outra coisa, uma boa prática é **evitar** sempre que possível [force unwrap](https://www.hackingwithswift.com/sixty/10/4/force-unwrapping), isso porque quando estamos expressando no código de forma explícita com o (!), estamos garantindo que aquela informação estará ali quando precisar ser acessada, acontece que podemos não ter essa informação e isso gerar um problema, crash, bug e afins. Uma das melhores maneiras de desembrulhar essas informações é utilizando [tanto if let quanto guard](https://www.hackingwithswift.com/quick-start/understanding-swift/when-to-use-guard-let-rather-than-if-let#:~:text=Swift%20gives%20us%20an%20alternative,stay%20around%20after%20the%20check), isso porque qualquer uma dessas opções te possibibilitará desembrulhar optionals garantindo um retorno ou um skip dos métodos garantindo pelo menos o não crash da aplicação. Para esse caso eu utilizaria um guard:

`guard let url = URL(string: Constant.environment) else { return NSError.invalidUrl }`

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Common/APIManager.swift
> +           }
mesma coisa de enumeradores para esses erros e tratamento!, veja que vc não tá tratando o erro em si, num projeto real vc precisa prover pelo menos uma solução para o backend entender o que está acontecendo na aplicação. Entendo que atualmente vc n tem muito o que prover de error, mas seria interessante dar uma lida e começar e pensar dessa forma qualitativa pra melhorar sua aplicação.
Aqui uma sugestão: https://felipelmota.gitbooks.io/the-swift-programming-language-in-portuguese-br/content/guia/tratamento_erro.html

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Common/Models/CarDetail.swift
> +    }
🚀

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Common/New Group/APIManager.swift
> +class APIManager {
vc fez uma nova declaração de APIManager aqui, num projeto real o próprio xcode te bloqueia , o ideal seria vc ter uma extension .. e extender a classe para adicionar quaisquer métodos que vc precise. Atenção a esse ponto

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Common/New Group/APIManager.swift
> +       task.resume()
vc percebeu que esse cara aqui é praticamente uma cópia do primeiro request q vc fez? se vc não usou o método load, pode excluir, pq trás redundância e pode causar problemas na hora do uso.

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Brands/Views/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
próximo desafio: FULL viewCode

2024-02-22 17:14 UTC, miziaalmeida commented on Service/APIManager.swift
> +class APIManager {
novamente a questão da class aqui ser redundante, depois exclua as que não são a base da APIManager, evita duplicidade de código, reduz escopo, e evita problemas de informações cruzando

2024-02-22 17:14 UTC, miziaalmeida commented on Service/APIManager.swift
> +    let baseURL = "https://parallelum.com.br/fipe/api/v1/carros"
usar Constants

2024-02-22 17:14 UTC, miziaalmeida commented on Service/APIManager.swift
> +            completion(nil)
perfeito uso, no próximo desafio iremos utilizar [Result](https://www.hackingwithswift.com/articles/161/how-to-use-result-in-swift), pra gente poder tratar esses erros aí.
para não lançar uma info nula vc poderia substituir por um NSError direto.. setando ele ali na completion q vc tá utilizando:

```
func performRequest<T: Codable>(endpoint: String, completion: @escaping (T?, Error?) -> Void) {
   guard let url = URL(string: baseURL + endpoint) else {
        print("URL inválida")
        let error = NSError(domain: "\(url)", code: 1001, userInfo: [NSLocalizedDescriptionKey: "Invalid URL"])
        completion(nil, error)
        return
    }
}
```

2024-02-22 17:14 UTC, miziaalmeida commented on Service/APIManager.swift
> +
praticamente todos os códigos aqui estão usando a mesma linha de decodificação, logo vc poderia reduzir essas informações utilizando 1 único método para o request e os demais apenas passando via parâmetros, isso vai te auxiliar na questão de duplicação de código, clean code, e em alguns princípios de SOLID, [esse material aqui](https://www.alura.com.br/artigos/solid?utm_term=&utm_campaign=%5BSearch%5D+%5BPerformance%5D+-+Dynamic+Search+Ads+-+Artigos+e+Conte%C3%BAdos&utm_source=adwords&utm_medium=ppc&hsa_acc=7964138385&hsa_cam=11384329873&hsa_grp=111087461203&hsa_ad=687448474447&hsa_src=g&hsa_tgt=aud-527303763294:dsa-2276348409543&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiA_tuuBhAUEiwAvxkgTglrXK9XtV9rXJeOEkOskJ2pw7nmnF0lzK15MxGe2zlIhPSYkCJ6NhoCIDAQAvD_BwE) usa uma base em C, mas vc vai conseguir entender como funciona e a importância de n ter redundância no código, a longo prazo códigos muito grandes ficam difíceis de manter e impossíveis de testar por conta do acoplamento e complexidade dos métodos. Vou te dar uma sugestão e se ficar interessante vc pode utilizar:
```
enum Constants {
    static let baseURL = "https://parallelum.com.br/fipe/api/v1/carros"
}

class APIManager {
    func getCarModels(with brandID: String, completion: @escaping (CarModel?) -> Void) {
        let endpoint = "/marcas/\(brandID)/modelos"
        self.performRequest(endpoint: endpoint, completion: completion)
    }
    
    func getCarYears(brandId: String, modelId: String, completion: @escaping ([Anos]?) -> Void) {
        let endpoint = "/marcas/\(brandId)/modelos/\(modelId)/anos"
        
        performRequest(endpoint: endpoint) { (years: [Anos]?) in
            completion(years)
        }
    }
    
    func getCarDetail(with brandId: String, and modelId: String, and yearId: String, completion: @escaping (CarDetail?) -> Void) {
        let endpoint = "/marcas/\(brandId)/modelos/\(modelId)/anos/\(yearId)"
        performRequest(endpoint: endpoint, completion: completion)
    }
    
    func performRequest<T: Codable>(endpoint: String, completion: @escaping (T?) -> Void) {
        guard let url = URL(string: Constants.baseURL + endpoint) else {
            print("URL inválida")
            completion(nil)
            return
        }
        
        var request = URLRequest(url: url)
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpMethod = "GET"
        
        let task = URLSession.shared.dataTask(with: request) { data, response, error in
            if let data = data {
                do {
                    let decodedData = try JSONDecoder().decode(T.self, from: data)
                    completion(decodedData)
                } catch {
                    print("Erro na decodificação JSON: \(error)")
                    completion(nil)
                }
            } else if let error = error {
                print(error)
                completion(nil)
            }
        }
        task.resume()
    }
}
```

2024-02-22 17:14 UTC, miziaalmeida commented on Service/APIManager.swift
> +
E quando vc for usar na sua viewModel, vc pode utilizar da seguinte forma:

```
func getDetailForYears(completion: @escaping (CarDetail) -> Void) {
        guard let brandId = brandId, let modelId = modelId, let yearId = yearId else {return}

        api.getCarDetail(with: brandId, and: modelId, and: yearId) { details in
            if let details = details {
                completion(details)
            }
        }
    }
```

2024-02-22 17:14 UTC, miziaalmeida commented on Service/APIManager.swift
> +
A ideia é deixar o que é responsabilidade de serviço, na camada de serviço e o que é regra de negócios dentro do seu campo de negócios. Existem outros pontos q vc pode tb tratar como por exemplo, n precisaríamos dessa completion sendo passada para a viewController no método de chamada ali do viewModel, vc poderia tratar os dados todos na sua viewModel e passar unicamente a resposta pra frente, q é a única coisa q importa pra viewController, mas poderemos melhorar isso no próximo desafio, utilizando protocolos, computed properties e outros tópicos do swift

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Common/Protocol/ServiceProtocol.swift
> +}
A ideia do protocolo é muito boa, mas como não está sendo utilizada aqui vc pode remover, no próximo desafio será uma obrigatoriedade

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Brands/Views/BrandsViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cell")
nos próximos desafios vamos criar células custom msm, essa célula mais básica pra esse desafio funciona, mas a ideia é vc entender como funciona a UITableView e tudo que compõe ela

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Brands/Views/BrandsViewController.swift
> +                 print("deu ruim po")
Importante sempre retirar comentários q n façam parte do contexto da feature.
Outra coisa, se vc n tiver uma view de erro planejada, tente pelo menos lançar um alert básico, isso garante que visualmente vc sabe que o problema tá ocorrendo e o usuário n fique sem contexto.

Exemplo:
```
func showAlert(message: String) {
    let alertController = UIAlertController(title: "Opa!", message: message, preferredStyle: .alert)

    let okAction = UIAlertAction(title: "OK", style: .default, handler: nil)
    alertController.addAction(okAction)

    if let topViewController = UIApplication.shared.keyWindow?.rootViewController {
        topViewController.present(alertController, animated: true, completion: nil)
    }
}
```

USO:
```
if let cars = cars {
                 self?.cars = cars
                 DispatchQueue.main.async {
                     self?.tableView.reloadData()
                 }
             } else {
                 showAlert(message: "Ocorreu um erro inesperado, estamos ajustando nossos serviços")
            }
```

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Brands/Views/BrandsViewController.swift
> +        navigationController?.pushViewController(nextViewController, animated: true)
Importante sempre entender se determinados códigos não fazem sentido estarem em métodos apartados a fim de garantir testes unitários. Uma maneira aqui seria criar uma função com o input dessa ViewController e o push da navigation, e esse método poderia inclusive estar na viewModel já q nessa situação vc n tem uma Presenter ou Router. Mais pra frente veremos a importância de Router ou Coordinator no contexto de navegação

Ex:

```
func goToNextController(with selectedBrand: Int, navigationController: UINavigationController) {
       let nextViewController = ModelsViewController()
       nextViewController.brandId = selectedBrand.codigo
       self.navigationController.pushViewController(nextViewController, animated: true)
}
```

USO:

```
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
         let selectedBrand = cars[indexPath.row]
       self.goToNextController(with selectedBrand, navigationController: self.navigation)
}

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +        view.layer.cornerRadius = 10
magic number

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +        label.font = .systemFont(ofSize: 24)
magic number

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +        modelLabel.numberOfLines = 0
magic number

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +        yearLabel.font = .systemFont(ofSize: 24)
magic number

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +        priceLabel.font = .boldSystemFont(ofSize: 30)
magic number, exemplo de possibilidade de uso:
```
enum Constants {
      enum Size {
           static let labelSize = 24.0
           static let boldLabelSize = 30.0
      }
}
```

USO

```
priceLabel.font = .boldSystemFont(ofSize: Constant.Size.boldLabelSize)
```

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +
vc usou um padrão em uma controller, e outro aqui, seria interessante vc manter a coerência do código:

utilize sempre esse padrão :
```

override func viewDidLoad() {
      setupViews
}


// para setar as informacoes de views e como elas serao configuradas
setupViews() {
    view.backgroundColor = .white
    setupViewHierarchy()
    setupConstraints()
    
    // aqui vc pode setar tb configuracoes de navigation
}

// para hierarquia das views (ou seja ordem como elas vão aparecer
private setupViewHierarchy() {
 view.addSubview(viewCentral)
        viewCentral.addSubview(brandLabel)
        viewCentral.addSubview(modelLabel)
        viewCentral.addSubview(yearLabel)
        viewCentral.addSubview(priceLabel)
}

// para as constraints da view
private setupConstraints() {
NSLayoutConstraint.activate([
            viewCentral.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            viewCentral.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            viewCentral.widthAnchor.constraint(equalToConstant: 390),
            viewCentral.heightAnchor.constraint(equalToConstant: 230),

            brandLabel.topAnchor.constraint(equalTo: viewCentral.topAnchor, constant: 25),
            brandLabel.leadingAnchor.constraint(equalTo: viewCentral.leadingAnchor, constant: 10),
            brandLabel.trailingAnchor.constraint(equalTo: viewCentral.trailingAnchor, constant: 10),

            modelLabel.topAnchor.constraint(equalTo: brandLabel.bottomAnchor, constant: 10),
            modelLabel.leadingAnchor.constraint(equalTo: viewCentral.leadingAnchor, constant: 10),
            modelLabel.trailingAnchor.constraint(equalTo: viewCentral.trailingAnchor, constant: 10),

            yearLabel.topAnchor.constraint(equalTo: modelLabel.bottomAnchor, constant: 10),
            yearLabel.leadingAnchor.constraint(equalTo: viewCentral.leadingAnchor, constant: 10),
            yearLabel.trailingAnchor.constraint(equalTo: viewCentral.trailingAnchor, constant: 10),

            priceLabel.topAnchor.constraint(equalTo: yearLabel.bottomAnchor, constant: 25),
            priceLabel.centerXAnchor.constraint(equalTo: viewCentral.centerXAnchor)
        ])
}
```

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +
Outra sugestão q coloquei aqui e é bom q vc dê uma lida sobre, importância de controle de acesso dos métodos e properties dentro de uma class/struct. Me refiro a vc setar public/private/internal
Um pouco de doc aqui -> https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol/
aqui -> https://www.alura.com.br/artigos/ios-swift-como-funcionam-modificadores-de-acesso

Em resumo aqui nessa class, n faz muito sentido pra mim permitir que outras classes que estejam porventura herdando essa controller ou mesmo construindo ela em outro lugar, possam alterar métodos dentro dela. Quando seto private para meus métodos e properties, estou informando que apenas a minha classe pode ver e modificar informações ali dentro desses métodos, e para as variáveis elas só poderão ser lidas (get), não modificadas (set), a não ser que isso seja um requerimento do q vc vá fazer, daí nós podemos utilizar métodos públicos ou delegates para passar informação pra frente.

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/View/DetailViewController.swift
> +        priceLabel.text = "Valor: \(details.valor)"
esse método passa/altera informação q vem do serviço, poderia estar na viewModel, e só receber lá no próprio método **getDetailsForYears** o details como parâmetro

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Detail/ViewModel/DetailViewModel.swift
> +        }
readeque conforme sugestão que está na class de serviço APIManager

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Models/View/ModelsViewController.swift
> +            tableView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
ajuste essas informações com os métodos adequados conforme apontei ali em cima utilizando os métodos setupViews, setupViewHierarchy, setupConstraints

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Models/ViewModel/ModelsViewModel.swift
> +                completion(cars)
readeque conforme sugestão que está na class de serviço APIManager

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Year/View/YearViewController.swift
> +        ])
ajuste essas informações com os métodos adequados conforme apontei ali em cima utilizando os métodos setupViews, setupViewHierarchy, setupConstraints

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Year/View/YearViewController.swift
> +        return years?.count ?? 0
faz um guard aqui pra n  ter que usar default, ou coloque o método pra recuperar na viewModel

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Year/View/YearViewController.swift
> +        return cell
muito bom!

2024-02-22 17:14 UTC, miziaalmeida commented on Fipe_Challenge/Features/Year/ViewModel/YearViewModel.swift
> +            completion(anos)
Readeque conforme sugestão que está na class de serviço APIManager

2024-02-22 17:14 UTC, miziaalmeida commented on Service/APIManager.swift
> +    }
Não vejo necessidade de vc ter uma class unicamente pra construir esse método. Se vc utilizasse um protocolo no service, faria mais sentido, mas aqui vc só tá aumentando escopo sem verdadeiramente ser algo q vai te trazer algum retorno em código/compilação. 
Como vc só tá setando nos viewModels uma constante referenciando o APIManager(), só ali eu já tenho acesso a toda classe, então esse cara aqui se torna meio inútil, pode readequar a proposta q eu fiz, ali mais em cima, e depois nós veremos como abstrair ainda mais essas informações.

2024-02-22 17:23 UTC, miziaalmeida commented
Pra completar o codeReview: seu desafio foi muito bom, faltaram algumas coisas que nós colocamos ali como pontos importantes pra vc trabalhar, mas no próximo desafio serão obrigatórios. O ponto positivo é que vc já vai ter uma boa base de código pra usar. 
Faz um README tb colocando o q vc aprendeu ou utilizou aqui, e um gif da aplicação funcionando.
Quanto as mudanças q eu solicitei, vc tem até sábado pra resolver o que for pertinente e interessante, no sábado eu dou like, aprovamos e fechamos seu desafio.
P A R A B É N S !!! 🚀  FOCO, q vai dar bom!

![image](https://github.com/miziaalmeida/FIPE-Desafio/assets/42849855/61719656-1c39-4b8c-ba1f-c98274dfe995)

2024-02-22 17:47 UTC, miziaalmeida requested changes

2024-02-22 17:47 UTC, miziaalmeida commented on Fipe_Challenge/Features/Brands/ViewModel/BrandsViewModel.swift
> +    var api = BrandsAPIManager()
Próximo tópico que abordaremos será injeção de dependências! https://medium.com/@caioschristino/construindo-uma-arquitetura-robusta-em-seu-projeto-ios-84776836e29d

2024-02-22 18:51 UTC, jeiellima commented on Fipe_Challenge/Common/Protocol/ServiceProtocol.swift
> +}
Já tinha sido removida

2024-02-22 18:52 UTC, jeiellima commented on Service/APIManager.swift
> +class APIManager {
Mas só tem uma class APIManager

2024-02-23 01:18 UTC, miziaalmeida commented on Service/APIManager.swift
> +class APIManager {
Aqui no teu código ela apareceu declarada em arquivos diferentes .. tenta ver se não deu algum problema na hora de você commitar ou renomeia a class principal pra vc saber onde que está a que aparece aqui como duplicada

2024-02-27 17:53 UTC, jeiellima commented on Fipe_Challenge/Common/APIManager.swift
> +
feito!

2024-02-27 17:54 UTC, jeiellima commented on Service/APIManager.swift
> +    }
feito!

2024-02-27 17:55 UTC, jeiellima commented on Fipe_Challenge/Features/Year/View/YearViewController.swift
> +        return years?.count ?? 0
feito!

2024-02-27 18:01 UTC, merged